### ISSUE TITLE
Ask for metric height in centimeters and not in meter

### ISSUE THREAD

**Issue by andbuitra** [lainsce/beemy#2]
Hello :)

Just as suggestion the height should be asked in centimeters instead of meters. This is because different countries have different separators for decimal places. Some times it's a comma, sometimes is a dot. This would help to avoid confusion, wrong results and would give more precision too

**Comment by lainsce** [comment]
I could add centimeters instead of meters. I just thought meters would work as default due to the BMI formula having to use meters.

**Comment by lainsce** [comment]
Fixed
