### ISSUE TITLE
Miscalculation

### ISSUE THREAD

**Issue by fabioizidio** [lainsce/beemy#5]
The Beemy app is not properly calculating the Body Mass Index. In the kg / m² mode, this index is equal to the body mass itself. Already in lb / ft² is zero.

**Comment by lainsce** [comment]
Sorry for me being confused, but, are you saying it's not calculating in lb / ft² correctly, giving you a index of value 0?

**Comment by lainsce** [comment]
Seems it's solved? Closing the issue then :D
