### ISSUE TITLE
Results get out of control

### ISSUE THREAD

**Issue by n1kolaa** [lainsce/beemy#6]
Not working on juno. all time result is 0

**Comment by lainsce** [comment]
I'm going to need more than this to solve your problem. What measurement units did you use? Did you input numbers correctly in the entries? etc.

**Comment by n1kolaa** [comment]
used cm and m for h, kg for mass no coma

**Comment by lainsce** [comment]
Try out for example, `1.85m` and `89kg`. Does it yield results?

**Comment by n1kolaa** [comment]
![screenshot from 2018-10-17 16-12-34](https://user-images.githubusercontent.com/1229327/47092550-831be100-d227-11e8-86e4-c602ad6bc3fa.png)
![screenshot from 2018-10-17 16-12-43](https://user-images.githubusercontent.com/1229327/47092560-88792b80-d227-11e8-800e-508a4e2e9fc3.png)

**Comment by lainsce** [comment]
Yeah that does not look right. I'll try doing a fix soon. :grimacing:

**Comment by lainsce** [comment]
Fixed in master!

**Comment by lainsce** [comment]
Fixed in master!

**Comment by lainsce** [comment]
Fixed
