### ISSUE TITLE
Grade label is wrong

### ISSUE THREAD

**Issue by yelloball** [lainsce/beemy#8]
https://github.com/lainsce/beemy/blob/286e501fd47bc1893e9b143ed0fb40ddc6f30773/src/MainWindow.vala#L151

Grade type: 24.1 to 30.0 should be Overweight instead of Obese.
Grade type: >30.0 should be Obese instead of Overweight.

**Comment by lainsce** [comment]
Oh wow, you're right. I may have traded both while coding and never noticed.

**Comment by lainsce** [comment]
Fixed!
